version: '3.4'

services:
    order.consumer:
        image: ${DOCKER_REGISTRY-}orderconsumer
        build:
            context: .
            dockerfile: Order.Consumer/Dockerfile
        environment:
            KAFKA_HOST: host.docker.internal:29092
            TOPIC_NEW_ORDER: product.new.product
            MONGO_DSN: mongodb://root:root@localhost:27017/meetup?authSource=admin