version: '3.4'

services:
    order.consumer:
        image: ${DOCKER_REGISTRY-}orderconsumer
        build:
            context: .
            dockerfile: Order.Consumer/Dockerfile
        depends_on:
            - kafka
        environment:
            KAFKA_HOST: host.docker.internal:29092
            TOPIC_NEW_ORDER: product.new.product

    zookeeper:
        image: confluentinc/cp-zookeeper:latest
        networks: 
            - broker-kafka
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:latest
        networks: 
            - broker-kafka
        depends_on:
            - zookeeper
        ports:
            - 9092:9092
            - 29092:29092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
            KAFKA_LISTENERS: INTERNAL://:9092, OUTSIDE://:29092
            KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://host.docker.internal:29092
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,OUTSIDE:PLAINTEXT            
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

networks: 
  broker-kafka:
    driver: bridge